lifo&fifo flask html
Novakovich/Lifo_and_Fifo pull request #10
Opened 2022-07-13 14:59 UTC by Novakovich

сделал часть ДЗ17 - может какие то вопросы или предложения

2022-07-13 15:24 UTC, oleg-chubin requested changes

2022-07-13 15:24 UTC, oleg-chubin commented on app.py
> +    {render_template('donation.html')}
тут можно переменные вовнутрь, разве нет?

2022-07-14 07:51 UTC, merged

2022-07-14 08:49 UTC, oleg-chubin commented on app.py
> +    return render_template('donation.html', item=item )
Супер

2022-07-14 08:49 UTC, oleg-chubin commented on templates/index.html
> +        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
блок head не нужен тут, он прийдет из инклюда

2022-07-14 08:53 UTC, Novakovich commented on templates/index.html
> +        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
я по аналогии с видео делал. не нужно так не нужно

2022-07-14 09:26 UTC, oleg-chubin commented on templates/index.html
> +        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
``` 
<nav class="navbar bg-light" style="margin-bottom: 10px;">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">CharityBar</span>
  </div>
</nav>
```
это встраиваемый

2022-07-14 09:26 UTC, Novakovich commented on templates/header.html
> +<!DOCTYPE html>
а наоборот можно? 
<!DOCTYPE html>
<html>
<head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
    <body>
        <nav class="navbar navbar-dark bg-primary">
            <div class="container-md">
                <a class="navbar-brand" href="/">CharityBar</a>
            </div>
        </nav>
    </body>
</html>

2022-07-14 09:29 UTC, oleg-chubin commented on templates/header.html
> +<!DOCTYPE html>
нет, помотрите, что получится. в результате

будут сложности с добавлением своих стилей, если вы это затащите.

тут упражнение именно на то чтоб разобраться как один работает, как другой - поэтому такие кейсы подобрал я

2022-07-14 09:42 UTC, Novakovich commented on templates/header.html
> +<!DOCTYPE html>
ну на данный момент ничего не поменялось. возможно если там дальше чем то заниматься то будет сложности

2022-07-14 09:43 UTC, oleg-chubin commented on templates/header.html
> +<!DOCTYPE html>
вы смотрите в отрисованном или в source code?

2022-07-14 09:58 UTC, Novakovich commented on templates/header.html
> +<!DOCTYPE html>
отрисованном

2022-07-14 09:59 UTC, Novakovich commented on templates/header.html
> +<!DOCTYPE html>
закомитил, надеюсь все правильно понял